language: node_js
node_js:
  - "stable"
on:
  push:
    branches: [main]
addons:
  chrome: stable
  
before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build