# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    paths: 
    - 'AngularAPIApp/**'
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AngularAPIApp

    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
       with:
          node-version: '14.x'
     - run: npm install
     - run: npm install -g @angular/cli 
     - run: ng build
